ALTER TABLE "events" ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "events" ADD COLUMN "styles" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "events" ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;
